services:

  postgres:
    image: postgres:15
    container_name: keycloak-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tftic@2026
    ports:
      - "5432:5432"
    volumes:
      - pg_keycloak:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.6.1
    container_name: keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: tftic@2026

      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8081:8080"
    depends_on:
      - postgres

    volumes:
      - ./keycloak-theme-for-kc-all-other-versions.jar:/opt/keycloak/providers/keycloakify-theme.jar

volumes:
  pg_keycloak: