
-- ROLE
INSERT INTO role (name) VALUES ('ROLE_ADMIN')ON CONFLICT DO NOTHING;
INSERT INTO role (name) VALUES ('ROLE_USER')ON CONFLICT DO NOTHING;
INSERT INTO role (name) VALUES ('ROLE_FORMATEUR')ON CONFLICT DO NOTHING;

-- KATA
INSERT INTO rank (style, type) VALUES ('KATA', 'STAGIAIRE')ON CONFLICT DO NOTHING;
INSERT INTO rank (style, type) VALUES ('KATA', 'DEPARTEMENTAL_B')ON CONFLICT DO NOTHING;
INSERT INTO rank (style, type) VALUES ('KATA', 'DEPARTEMENTAL_A')ON CONFLICT DO NOTHING;
INSERT INTO rank (style, type) VALUES ('KATA', 'REGIONAL_B')ON CONFLICT DO NOTHING;
INSERT INTO rank (style, type) VALUES ('KATA', 'REGIONAL_A')ON CONFLICT DO NOTHING;
INSERT INTO rank (style, type) VALUES ('KATA', 'NATIONAL_B')ON CONFLICT DO NOTHING;
INSERT INTO rank (style, type) VALUES ('KATA', 'NATIONAL_A')ON CONFLICT DO NOTHING;
INSERT INTO rank (style, type) VALUES ('KATA', 'INTERNATIONAL_B')ON CONFLICT DO NOTHING;
INSERT INTO rank (style, type) VALUES ('KATA', 'INTERNATIONAL_A')ON CONFLICT DO NOTHING;
INSERT INTO rank (style, type) VALUES ('KATA', 'MONDIAL_B')ON CONFLICT DO NOTHING;
INSERT INTO rank (style, type) VALUES ('KATA', 'MONDIAL_A')ON CONFLICT DO NOTHING;

-- KUMITE
INSERT INTO rank (style, type) VALUES ('KUMITE', 'STAGIAIRE')ON CONFLICT DO NOTHING;
INSERT INTO rank (style, type) VALUES ('KUMITE', 'DEPARTEMENTAL_B')ON CONFLICT DO NOTHING;
INSERT INTO rank (style, type) VALUES ('KUMITE', 'DEPARTEMENTAL_A')ON CONFLICT DO NOTHING;
INSERT INTO rank (style, type) VALUES ('KUMITE', 'REGIONAL_B')ON CONFLICT DO NOTHING;
INSERT INTO rank (style, type) VALUES ('KUMITE', 'REGIONAL_A')ON CONFLICT DO NOTHING;
INSERT INTO rank (style, type) VALUES ('KUMITE', 'NATIONAL_B')ON CONFLICT DO NOTHING;
INSERT INTO rank (style, type) VALUES ('KUMITE', 'NATIONAL_A')ON CONFLICT DO NOTHING;
INSERT INTO rank (style, type) VALUES ('KUMITE', 'INTERNATIONAL_B')ON CONFLICT DO NOTHING;
INSERT INTO rank (style, type) VALUES ('KUMITE', 'INTERNATIONAL_A')ON CONFLICT DO NOTHING;
INSERT INTO rank (style, type) VALUES ('KUMITE', 'MONDIAL_B')ON CONFLICT DO NOTHING;
INSERT INTO rank (style, type) VALUES ('KUMITE', 'MONDIAL_A')ON CONFLICT DO NOTHING;